In [1]:
import pandas as pd

In [2]:
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['Aammar', 'Amaar', 'Hamza', 'Hazma'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}

# make pandas dataframe
df = pd.DataFrame(data=data)

In [3]:
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.   Amaar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hazma       200.0       150.0

In [4]:
# standardizing the data format
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1         NaN         U.S.A.   Amaar       200.0       150.0
2         NaN        America   Hamza         NaN       300.0
3         NaN  United States   Hazma       200.0       150.0

In [5]:
# Impute fill the date and try another method to complete the date format inconsistencies
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].ffill().bfill()
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  2021-12-01         U.S.A.   Amaar       200.0       150.0
2  2021-12-01        America   Hamza         NaN       300.0
3  2021-12-01  United States   Hazma       200.0       150.0

In [6]:
# Harmonize the name of the country
country_mapping = {'USA': 'United States', 'U.S.A.': 'United States','America': 'United States'}
df['country'] = df['country'].replace(country_mapping)
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
1  2021-12-01  United States   Amaar       200.0       150.0
2  2021-12-01  United States   Hamza         NaN       300.0
3  2021-12-01  United States   Hazma       200.0       150.0

In [7]:
# correct the typographical mistakes in name
name_mapping = {'Amaar': 'Aammar', 'Hazma': 'Hamza'}
df['name'] = df['name'].replace(name_mapping)
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
1  2021-12-01  United States  Aammar       200.0       150.0
2  2021-12-01  United States   Hamza         NaN       300.0
3  2021-12-01  United States   Hamza       200.0       150.0

In [8]:
# remove duplicates
df = df.drop_duplicates(subset="name")
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
2  2021-12-01  United States   Hamza         NaN       300.0

In [9]:
# for demonstration, let's assume sales_2021 should always be higher than sales_2020
# we'll remove rows where this condition in not met
df = df.drop(df[df['sales_2021'] <= df['sales_2020']].index)
df.head()

         date        country    name  sales_2020  sales_2021
0  2021-12-01  United States  Aammar       100.0         NaN
2  2021-12-01  United States   Hamza         NaN       300.0